### ISSUE TITLE
misp2memcached error

### ISSUE THREAD

**Issue by homa1978** [j91321/MISP2memcached#1] opened 2021-03-04 07:15 UTC
Hi !

I tried your project but get the followng error:

Traceback (most recent call last):
  File "./misp2memcached.py", line 26, in <module>
    memcached = outputs.memcached.Memcached(config['memcached']['host'], config['memcached']['port'])
  File "/opt/asm/threatintel/MISP2memcached/outputs/memcached.py", line 17, in __init__
    self.client = pymemcache.client.base.Client((self.host, self.port))
AttributeError: module 'pymemcache' has no attribute 'client'

memcached is running on port 11211

**Comment by homa1978** [comment] 2021-03-04 07:24
I think there is the class Client missing. Can you add these please to the repo

**Comment by j91321** [comment] 2021-03-05 09:45
I'm having trouble replicating your error can you please provide following information?
- python version
- pymemcache package version

**Comment by j91321** [comment] 2021-03-10 18:20
ping @homa1978

**Comment by homa1978** [comment] 2021-03-16 07:49
I could resolve the problem with adding

from pymemcache.client.base import Client

into outputs/memcached.py

**Comment by j91321** [comment] 2021-03-16 09:55
Closing this, not sure why that error would appear since the code imports pymemcache and then properly uses the Client class
and I failed to reproduce it.

```
self.client = pymemcache.client.base.Client((self.host, self.port))
```

**Closed as completed by j91321** 2021-03-16 09:55 UTC
Labels: bug, wontfix
